### ISSUE TITLE
Pandora FMS Server 'Pandora' unhandled error.

### ISSUE THREAD

**Issue by hphc** [pandorafms/pandorafms#106]
Getting continuous error logs on Pandora FMS server

[**E] 'pandora': DBD::mysql::st execute failed: Unknown column 'update_secondary_groups' in 'field list' at /usr/lib/perl5/PandoraFMS/DB.pm line 756.**

I was not able to find out the table where i need to add the column name .

**Comment by nramon** [comment]
Hi @hphc,

That error is probably caused by a partial update. Check your current minor release version (the _MR X_ part of the version string you see in the footer of your Pandora FMS Console) and update your database schema to the latest version. [Here](https://wiki.pandorafms.com/index.php?title=Pandora:Documentation_en:Anexo_Upgrade#Version_7.0NG_.28_Rolling_Release_.29)'s how to do it. (e.g., if you're on _MR 8_ and you see a _mr/9.sql_ file, apply it as described in the docs.)

That column in particular belongs to the table _tagente_.

**Comment by hphc** [comment]
Hi @nramon, Thanks a ton. 
Problem got resolved after updating the db.
