### ISSUE TITLE
pandorafms-console docker image  version 6 and latest version exception

### ISSUE THREAD

**Issue by cloud411716** [pandorafms/pandorafms#139]
I use `docker run -idt -p 80:80 -p 8022:8022 -p 8023:8023 -e PANDORA_DB_HOST=10.82.12.238:3306 -e PANDORA_DB_NAME=pandora -e  PANDORA_DB_USER=pandora -e  PANDORA_DB_PASSWORD=pandora  tdsis/pandorafms-console:latest` to start the container but failed,there are a lot of error messages like this "mv: cannot remove `/tmp/pandorafms/pandora_console/vendor/swiftmailer/swiftmailer/tests/unit/Swift/Transport/EsmtpTransportTest.php': No such file or directory".

**Comment by rafaelameijeiras** [comment]
Hello @aaron1989041 its nice to meet you.

You are using a non official PandoraFMS image, so we cant give you support over it. Also this image is prety old, 4 years old? really? 

A lot of things has been change since 2016 so better not use this image.

The good news are we have an official Pandora FMS image you can use, you may find it on our official dockerhub repo:
https://hub.docker.com/u/pandorafms

And also if you want to customize and create your own custom image you can fallow this tutorial on our official youtube channel:
https://www.youtube.com/watch?v=GbKBLCZmwJo

Hope you find this comment useful.

**Comment by cloud411716** [comment]
> Hello @aaron1989041 its nice to meet you.
> 
> You are using a non official PandoraFMS image, so we cant give you support over it. Also this image is prety old, 4 years old? really?
> 
> A lot of things has been change since 2016 so better not use this image.
> 
> The good news are we have an official Pandora FMS image you can use, you may find it on our official dockerhub repo:
> https://hub.docker.com/u/pandorafms
> 
> And also if you want to customize and create your own custom image you can fallow this tutorial on our official youtube channel:
> https://www.youtube.com/watch?v=GbKBLCZmwJo
> 
> Hope you find this comment useful.

I'm really sorry to post the wrong docker start command,I actually use the official pandorafms/pandorafms-console image and those error messages only appear when using official image.When using tdsis/pandora-console image,everything goes well.  
I tried to run the latest official image,but official site's online document does not fit very well with the latest docker image,some contents and pictures in online document look different from the latest docker image,so I chose version 6.
