### ISSUE TITLE
[Pandora Installation for Windows] Pandora FMS Server address - empty value breaks Nginx config

### ISSUE THREAD

**Issue by stonio** [pandorafms/pandorafms#75]
During Windows installation I have set an empty value in field **Nginx Setup** > **Pandora FMS Server address**. This has corrupted Nginx configuration so application cannot start. Please make this field mandatory (or set a default value) in Windows installer.

## Steps to reproduce bug on Windows

* Download and execute Windows installer (`pandorafms_server_6.0SP4_x86_64.exe`)
* In panel **Nginx Setup** (see [screenshot]( http://wiki.pandorafms.com/index.php?title=File:Pandora_server_install_windows_05_eng.png)):
* Change value of field **Pandora FMS Server address** to empty (no value).
* Click on button **Install** to complete installation

Pandora FMS cannot start because Nginx is badly configured (see errors in `C:\PandoraFMS\nginx\logs\error.log`).

## Workaround

Edit manually `C:\PandoraFMS\nginx\conf\nginx.conf` line 25:
```
        server_name  $hostname;
```

**Comment by fbsanchez** [comment]
Hello,

This is a known issue, the field should contain the FQDN of the server in
the Nginx based installer in order to serve the pages correctly.

This has change in the new releases, providing now with Apache 2.4. In the
new version of the installer there's no need to set the FQDN, being
available the service only with keyword "localhost".

Hope it helps

Kind regards,




2016-11-24 17:09 GMT+01:00 stonio <notifications@github.com>:
