### ISSUE TITLE
No available data to show

### ISSUE THREAD

**Issue by taocnrut** [pandorafms/pandorafms#77]
I am testing pandora via docker and had 

Is there anything I should do to show data and graphs of agent submitted modules (Module definition "Apprentice mode" is enabled):
![image](https://cloud.githubusercontent.com/assets/9872687/22171343/ba50f5d8-df8b-11e6-9ba1-f33656aafeea.png)

Agent's log file is showing:
2017/01/21 03:36:13 - [log] - Running as user root
2017/01/21 03:36:13 - [setup] - server_ip is 10.99.5.7
2017/01/21 03:36:13 - [setup] - server_path is /var/spool/pandora/data_in
2017/01/21 03:36:13 - [setup] - temporal is /tmp
2017/01/21 03:36:13 - [setup] - logfile is /var/log/pandora/pandora_agent.log
2017/01/21 03:36:13 - [setup] - interval is 30
2017/01/21 03:36:13 - [setup] - debug is 0
2017/01/21 03:36:13 - [setup] - udp_server is 1
2017/01/21 03:36:13 - [setup] - udp_server_port is 41122
2017/01/21 03:36:13 - [setup] - udp_server_auth_address is 10.99.5.7
2017/01/21 03:36:13 - [setup] - agent_name is mns-thq-monitor-1
2017/01/21 03:36:13 - [setup] - group is Servers
2017/01/21 03:36:13 - [setup] - address is 10.99.7.3
2017/01/21 03:36:13 - [setup] - server_port is 41121
2017/01/21 03:36:13 - [setup] - transfer_mode is tentacle
2017/01/21 03:36:13 - [setup] - remote_config is 0
2017/01/21 03:36:13 - [setup] - xml_buffer is 1
2017/01/21 03:36:13 - [setup] - temporal_min_size is 1024
2017/01/21 03:36:13 - [log] - Thread is disabled.

Config file of agent is
[pandora_agent.conf.txt](https://github.com/pandorafms/pandorafms/files/720862/pandora_agent.conf.txt)

I'd like to specify all the module configuration on agent, and server to just swallow whatever I configure on agent. Is that possible?

**Comment by fbsanchez** [comment]
Hello!

Since the data appears in the Pandora console, the agent's configuration file is no necessary.

Please check the timezone is set properly in all docker containers:

docker exec $DOCKER_ID date


Also you can check the DB directly from the DB extensions: 

Admin extensions > DB Maintenance > DB manager

http://localhost/pandora_console/index.php?sec=gdbman&sec2=extensions/dbmanager

And run the next query to check if really are data stored in the DB:
select datos, from_unixtime(utimestamp) from tagente_datos where id_agente_modulo = XXX order by 2 DESC Limit 50;

Get the id_agente_modulo value from the module's administration page:

![image](https://cloud.githubusercontent.com/assets/12999095/22176106/fa15bac4-e002-11e6-8c6e-519072600ae2.png)


Hope it helps you,

**Comment by taocnrut** [comment]
Yes, it was timezone conflict, since the data started to show after a couple of hours.
