### ISSUE TITLE
Pandora server doesn't have enc directory

### ISSUE THREAD

**Issue by tanimientras** [pandorafms/pandorafms#96]
Default /etc/pandora/pandora_server.conf contains:

```
# Directory were additional enc files for the XML parser are located.
enc_dir /usr/share/pandora_server/enc/
```

but when running pandora-server image, it complains with:

> Nov 15 08:41:23 pc pandora-server[5758]:  [WARNING] Error opening directory /usr/share/pandora_server/enc/: No such file or directory

**Comment by nramon** [comment]
Hi tanimientras, that's just a controlled warning, you can ignore it. _enc_dir_ has a default value so that Japanese encodings are loaded by default when installing Pandora FMS from the official ISO image.                               
                                                                                                                                                                                                                                          
We changed the way encoding maps are loaded anyway, so next time you upgrade your Pandora FMS server the warning will go away.                                                                                                            
                                                                                                                                                                                                                                          
Thank you for taking the time to report this issue.
